export interface Vibe {
  id: number;
  text: string;
  category: 'humor' | 'optimistic' | 'depressive' | 'general' | 'motivational' | 'punchline' | 'meme';
}

export const vibes: Vibe[] = [
  // ============================================
  // HUMOR (1 → 80)
  // ============================================
  { id: 1, text: "\"I treat my portfolio like my plants: ignore it for 6 months and pray it’s still alive.\"", category: "humor" },
  { id: 2, text: "\"I told my kids that crypto is the future. They asked if the future also includes dinner.\"", category: "humor" },
  { id: 3, text: "\"Crypto whales don’t drink water. They hydrate with your liquidated positions.\"", category: "humor" },
  { id: 4, text: "\"I'm not saying I'm early to crypto, but my Metamask still has the default fox stare.\"", category: "humor" },
  { id: 5, text: "\"My wallet isn’t empty. It’s just optimized for lightweight transactions.\"", category: "humor" },
  { id: 61, text: "\"I bought Bitcoin in 2017. Still waiting for my personality to recover.\"", category: "humor" },
  { id: 62, text: "\"There are two types of traders: liars and people who panic sold at -40%.\"", category: "humor" },
  { id: 63, text: "\"My strategy? Buy the top, sell the hopium.\"", category: "humor" },
  { id: 64, text: "\"I told my kids they're my seed phrase. They told me I'm not safe to store anything.\"", category: "humor" },
  { id: 65, text: "\"My girlfriend asked when I’ll cash out. I asked when she’ll stop asking.\"", category: "humor" },
  { id: 66, text: "\"Not a whale, not a minnow. I'm a plankton with WiFi.\"", category: "humor" },
  { id: 67, text: "\"A crypto investor with a PhD is still just a professional bagholder.\"", category: "humor" },
  { id: 68, text: "\"Bought NFTs to change my life. They did: now I'm broke and philosophical.\"", category: "humor" },
  { id: 69, text: "\"My portfolio and my dating life have one thing in common: no stability.\"", category: "humor" },
  { id: 70, text: "\"Therapy is expensive. Watching Bitcoin pump is free.\"", category: "humor" },
  { id: 71, text: "\"The only goat I ever owned got rugged on-chain.\"", category: "humor" },
  { id: 72, text: "\"I told my wife we're getting a Lambo one day. She asked me to stop manifesting poverty.\"", category: "humor" },
  { id: 73, text: "\"Crypto couples don’t divorce. They just emotionally stake each other forever.\"", category: "humor" },
  { id: 74, text: "\"I'm not addicted to crypto. I just enjoy daily adrenaline attacks.\"", category: "humor" },
  { id: 75, text: "\"FOMO makes you broke. FUD makes you lonely. Choose wisely.\"", category: "humor" },
  { id: 76, text: "\"Put all my savings in crypto. Now my mom calls me her 'digital disappointment'.\"", category: "humor" },
  { id: 77, text: "\"Bitcoin crossed the road to escape people's price predictions.\"", category: "humor" },
  { id: 78, text: "\"I told my kids they're my inheritance. They asked if there’s a version without volatility.\"", category: "humor" },
  { id: 79, text: "\"If you're right 10% of the time in crypto, congrats — you're a legend.\"", category: "humor" },
  { id: 80, text: "\"I'm not losing money. I'm donating liquidity to the ecosystem.\"", category: "humor" },

  // ============================================
  // OPTIMISTIC (81 → 105)
  // ============================================
  { id: 81, text: "\"Every dip is just the market letting you buy the future at a discount.\"", category: "optimistic" },
  { id: 82, text: "\"Web3 is still early — everything feels broken because we're building it live.\"", category: "optimistic" },
  { id: 83, text: "\"Blockchain won’t change everything overnight. Just most things eventually.\"", category: "optimistic" },
  { id: 84, text: "\"Financial freedom starts with a wallet and a little courage.\"", category: "optimistic" },
  { id: 85, text: "\"Trust code, not banks. The code hasn’t lied to you… yet.\"", category: "optimistic" },
  { id: 86, text: "\"Next bull run? You'll laugh at the prices you hesitated to buy.\"", category: "optimistic" },
  { id: 87, text: "\"We're not the users of the future — we're the beta testers.\"", category: "optimistic" },
  { id: 88, text: "\"Corrections are just the market stretching before a marathon.\"", category: "optimistic" },
  { id: 89, text: "\"The blockchain keeps receipts. And history will too.\"", category: "optimistic" },
  { id: 90, text: "\"Call it a bubble if you want — I call it evolution.\"", category: "optimistic" },
  { id: 91, text: "\"Institutions are coming. And they’re bringing real bags.\"", category: "optimistic" },
  { id: 92, text: "\"Crypto is a bet on humans becoming smarter. Risky, but fun.\"", category: "optimistic" },
  { id: 93, text: "\"Smart contracts get upgraded. So do we.\"", category: "optimistic" },
  { id: 94, text: "\"We're living through the greatest wealth shift ever. Seatbelt on.\"", category: "optimistic" },
  { id: 95, text: "\"The code doesn't care who you are — that’s real equality.\"", category: "optimistic" },
  { id: 96, text: "\"Holding isn’t laziness. It’s strategy in its purest form.\"", category: "optimistic" },
  { id: 97, text: "\"Next cycle? We’re entering with experience, trauma, and memes.\"", category: "optimistic" },
  { id: 98, text: "\"Crypto will outlive us. And that’s kind of beautiful.\"", category: "optimistic" },
  { id: 99, text: "\"The revolution already started. You're just choosing your role.\"", category: "optimistic" },
  { id: 100, text: "\"You're not early. You're exactly on time.\"", category: "optimistic" },
  { id: 101, text: "\"Builders shape the future. You're one of them.\"", category: "optimistic" },
  { id: 102, text: "\"Every failed project is a tutorial in disguise.\"", category: "optimistic" },
  { id: 103, text: "\"Blockchain is bigger than any one cycle.\"", category: "optimistic" },
  { id: 104, text: "\"We’re not holding coins. We’re holding possibility.\"", category: "optimistic" },
  { id: 105, text: "\"The best chapter hasn’t even started.\"", category: "optimistic" },

  // ============================================
  // DEPRESSIVE (106 → 130)
  // ============================================
  { id: 106, text: "\"Checked my portfolio. Then checked if sadness qualifies as a tax write-off.\"", category: "depressive" },
  { id: 107, text: "\"I hodl so hard my emotions are permanently staked.\"", category: "depressive" },
  { id: 108, text: "\"My strategy: buy high, sell low, reflect deeply.\"", category: "depressive" },
  { id: 109, text: "\"My portfolio isn’t down. It’s just exploring the basement.\"", category: "depressive" },
  { id: 110, text: "\"Came for financial freedom. Left with personality damage.\"", category: "depressive" },
  { id: 111, text: "\"Stopped checking prices. Inner peace restored. Wallet ruined.\"", category: "depressive" },
  { id: 112, text: "\"My portfolio chart is flatter than my motivation.\"", category: "depressive" },
  { id: 113, text: "\"Tried explaining crypto to my wife. She googled divorce lawyers.\"", category: "depressive" },
  { id: 114, text: "\"Only thing I sold at the top was my hardware wallet on eBay.\"", category: "depressive" },
  { id: 115, text: "\"Whatever I’m holding isn’t a bag anymore — it’s an artifact.\"", category: "depressive" },
  { id: 116, text: "\"The only thing going up is my stress ratio.\"", category: "depressive" },
  { id: 117, text: "\"Lost less money in my divorce than in the bear market.\"", category: "depressive" },
  { id: 118, text: "\"The code didn’t fail me. My timing did.\"", category: "depressive" },
  { id: 119, text: "\"I don’t invest. I emotionally sponsor tokens.\"", category: "depressive" },
  { id: 120, text: "\"My portfolio resembles my dating life: unpredictable and disappointing.\"", category: "depressive" },
  { id: 121, text: "\"Told my kids they're my inheritance. They said they'd rather inherit stability.\"", category: "depressive" },
  { id: 122, text: "\"I'm committed to crypto. Mostly the pain part.\"", category: "depressive" },
  { id: 123, text: "\"Portfolio volatility matches my mental state.\"", category: "depressive" },
  { id: 124, text: "\"I've been hodling so long I forgot dinner costs money.\"", category: "depressive" },
  { id: 125, text: "\"Not broke. Just overly dedicated to losing money creatively.\"", category: "depressive" },
  { id: 126, text: "\"My portfolio promises a lot. Delivers nothing.\"", category: "depressive" },
  { id: 127, text: "\"Told my wife she’s getting a Lambo one day. She told me to get a job first.\"", category: "depressive" },
  { id: 128, text: "\"I'm not losing money — I'm paying tuition to the blockchain gods.\"", category: "depressive" },
  { id: 129, text: "\"Put everything into crypto. Now I live in a risk-adjusted lifestyle.\"", category: "depressive" },
  { id: 130, text: "\"Not a whale. Not a minnow. Just a sad aquarium accessory.\"", category: "depressive" },

  // ============================================
  // GENERAL (131 → 150)
  // ============================================
  { id: 131, text: "\"Mood of the day: bullish on caffeine, bearish on responsibilities.\"", category: "general" },
  { id: 132, text: "\"Feeling like a degen in a world full of spreadsheets.\"", category: "general" },
  { id: 133, text: "\"Energy level today: sideways like a stablecoin.\"", category: "general" },
  { id: 134, text: "\"Currently looking for a sugar daddy who believes in staking.\"", category: "general" },
  { id: 135, text: "\"Emotionally stable, financially rugged.\"", category: "general" },
  { id: 136, text: "\"Status: alive but not liquid.\"", category: "general" },
  { id: 137, text: "\"Just because you're paranoid doesn't mean the charts aren't hunting you.\"", category: "general" },
  { id: 138, text: "\"Not rich, but my transaction history is wild.\"", category: "general" },
  { id: 139, text: "\"Investment strategy: vibes only.\"", category: "general" },
  { id: 140, text: "\"Not losing money. Just discovering new financial floors.\"", category: "general" },
  { id: 141, text: "\"I'm not addicted to crypto. I'm emotionally leveraged.\"", category: "general" },
  { id: 142, text: "\"Not a whale, not a minnow — just a confused aquatic creature.\"", category: "general" },
  { id: 143, text: "\"Paying for therapy? No thanks. I’ll just check charts at 3 AM.\"", category: "general" },
  { id: 144, text: "\"Not broke. Just financially free… from money.\"", category: "general" },
  { id: 145, text: "\"Market dumped? So did my mood.\"", category: "general" },
  { id: 146, text: "\"I'm not volatile. The world just reacts poorly to me.\"", category: "general" },
  { id: 147, text: "\"Bearish on everything except snacks.\"", category: "general" },
  { id: 148, text: "\"My wallet is light but my delusion is heavy.\"", category: "general" },
  { id: 149, text: "\"I'm fine. No, really. Just fine. Totally fine.\"", category: "general" },
  { id: 150, text: "\"I'm not broke. I'm strategically illiquid.\"", category: "general" },

  // ============================================
  // MOTIVATIONAL (151 → 170)
  // ============================================
  { id: 151, text: "\"Diamond hands start in the mind before the wallet.\"", category: "motivational" },
  { id: 152, text: "\"Every pro was once a confused degen clicking 'confirm' too fast.\"", category: "motivational" },
  { id: 153, text: "\"Time in the market beats timing the panic.\"", category: "motivational" },
  { id: 154, text: "\"Fear passes. Regret stays. Choose wisely.\"", category: "motivational" },
  { id: 155, text: "\"You’re not chasing pumps — you’re chasing progress.\"", category: "motivational" },
  { id: 156, text: "\"Patience pays. Impatience screenshots charts.\"", category: "motivational" },
  { id: 157, text: "\"Every dip reveals what kind of investor you are.\"", category: "motivational" },
  { id: 158, text: "\"Invest in yourself first. Everything else compounds.\"", category: "motivational" },
  { id: 159, text: "\"Uncertainty is the playground of opportunity.\"", category: "motivational" },
  { id: 160, text: "\"Small steps today, big wins tomorrow.\"", category: "motivational" },
  { id: 161, text: "\"Consistency beats brilliance.\"", category: "motivational" },
  { id: 162, text: "\"If you’re still here, you’re already ahead of most.\"", category: "motivational" },
  { id: 163, text: "\"Volatility only hurts those without conviction.\"", category: "motivational" },
  { id: 164, text: "\"Patience is the final boss of crypto.\"", category: "motivational" },
  { id: 165, text: "\"Pain teaches. Profit rewards.\"", category: "motivational" },
  { id: 166, text: "\"Learn enough to trust yourself.\"", category: "motivational" },
  { id: 167, text: "\"You can’t control the market. But you can control yourself.\"", category: "motivational" },
  { id: 168, text: "\"Every cycle creates new winners. You could be one.\"", category: "motivational" },
  { id: 169, text: "\"You don’t need luck — just perseverance.\"", category: "motivational" },
  { id: 170, text: "\"The best thing you can invest in is your future self.\"", category: "motivational" },

  // ============================================
  // PUNCHLINE (171 → 190)
  // ============================================
  { id: 171, text: "\"Wen moon? Wen Lambo? Wen salary?\"", category: "punchline" },
  { id: 172, text: "\"Not your keys, not your coins. Not your drive, not your future.\"", category: "punchline" },
  { id: 173, text: "\"Buy rumors, sell news, regret everything.\"", category: "punchline" },
  { id: 174, text: "\"To the moon — but the fuel tank is unpredictable.\"", category: "punchline" },
  { id: 175, text: "\"HODL until people think you’re stubborn, then HODL more.\"", category: "punchline" },
  { id: 176, text: "\"DYOR: or cry later, your choice.\"", category: "punchline" },
  { id: 177, text: "\"FOMO fades. Regret doesn’t.\"", category: "punchline" },
  { id: 178, text: "\"Bull markets build ego. Bear markets build character.\"", category: "punchline" },
  { id: 179, text: "\"Buy low, sell high. Easy in theory, legendary in practice.\"", category: "punchline" },
  { id: 180, text: "\"Timing the market? Bro, I can’t even time my sleep schedule.\"", category: "punchline" },
  { id: 181, text: "\"Wen moon? When you're emotionally ready.\"", category: "punchline" },
  { id: 182, text: "\"Not your keys, not your bags, not your legacy.\"", category: "punchline" },
  { id: 183, text: "\"Sell the news? First understand the news.\"", category: "punchline" },
  { id: 184, text: "\"To the moon — but pack emotional insurance.\"", category: "punchline" },
  { id: 185, text: "\"HODL until your bags become your personality.\"", category: "punchline" },
  { id: 186, text: "\"DYOR or RIP your portfolio.\"", category: "punchline" },
  { id: 187, text: "\"Miss the next Bitcoin? That regret lasts forever.\"", category: "punchline" },
  { id: 188, text: "\"Bull markets give gains, bear markets give wisdom.\"", category: "punchline" },
  { id: 189, text: "\"Buying the dip is easy. Having money left is the challenge.\"", category: "punchline" },
  { id: 190, text: "\"Catching bottoms is like catching falling knives: impressive and bloody.\"", category: "punchline" },

  // ============================================
  // MEME (191 → 390)
  // 4 Sous-thèmes :
  //   Farcaster (191–230)
  //   Base (231–260)
  //   Ultra-degen (261–290)
  //   Trader/NFT/Airdrop (291–320)
  // ============================================

  // ---------- FARCASTER MEMES ----------
  { id: 191, text: "\"Me checking Farcaster every 5 minutes like it’s my portfolio.\"", category: "meme" },
  { id: 192, text: "\"When your cast gets 1 like and it's you from your alt account.\"", category: "meme" },
  { id: 193, text: "\"The feeling when a whale recasts your meme: instant dopamine.\"", category: "meme" },
  { id: 194, text: "\"Following 300 people, still only seeing the same 12 casters.\"", category: "meme" },
  { id: 195, text: "\"POV: you send a perfect cast and forget to attach the image.\"", category: "meme" },
  { id: 196, text: "\"When your cast gets traction and you pretend you’re not refreshing.\"", category: "meme" },
  { id: 197, text: "\"Farcaster notifications hit harder than my real-life accomplishments.\"", category: "meme" },
  { id: 198, text: "\"My social life is now measured in recasts.\"", category: "meme" },
  { id: 199, text: "\"If vibes were tokens, I'd be fully diluted.\"", category: "meme" },
  { id: 200, text: "\"I joined Farcaster to meet people. Now I only meet new bags.\"", category: "meme" },
  { id: 201, text: "\"My reaction when Warpcast is down: panic-level-ETH-liquidation.\"", category: "meme" },
  { id: 202, text: "\"When someone follows you and you pretend you’re not excited.\"", category: "meme" },
  { id: 203, text: "\"Every cast is a micro gamble on human attention.\"", category: "meme" },
  { id: 204, text: "\"Looking for alpha on Farcaster like it’s hidden behind a purple button.\"", category: "meme" },
  { id: 205, text: "\"Farcaster drama is my second favorite entertainment after market crashes.\"", category: "meme" },
  { id: 206, text: "\"Me posting memes hoping a VC sees them and funds me.\"", category: "meme" },
  { id: 207, text: "\"I only cast during pumps. I emotionally dump during dips.\"", category: "meme" },
  { id: 208, text: "\"Discover feed: 10% smart devs, 90% degens saying gm.\"", category: "meme" },
  { id: 209, text: "\"If casts earned tokens, I’d be a multi-billionaire.\"", category: "meme" },
  { id: 210, text: "\"I don’t need therapy, I need more recasts.\"", category: "meme" },

  // + 10 nouvelles
  { id: 211, text: "\"Me opening Farcaster before emails because priorities.\"", category: "meme" },
  { id: 212, text: "\"Casting something witty, then deleting it 3 seconds later.\"", category: "meme" },
  { id: 213, text: "\"When someone recasts you and you're instantly best friends.\"", category: "meme" },
  { id: 214, text: "\"Every cast is a gamble: will it flop or will it moon?\"", category: "meme" },
  { id: 215, text: "\"Discover feed is just the universe telling me who’s funnier than me.\"", category: "meme" },
  { id: 216, text: "\"Posting a meme on Farcaster counts as productivity, right?\"", category: "meme" },
  { id: 217, text: "\"I cast my feelings because therapy is expensive.\"", category: "meme" },
  { id: 218, text: "\"When your cast hits 20 likes and you think you're famous now.\"", category: "meme" },
  { id: 219, text: "\"Farcaster profiles: 10% info, 90% personality crisis.\"", category: "meme" },
  { id: 220, text: "\"Opening the app and immediately forgetting what I came to post.\"", category: "meme" },

  // ---------- BASE CHAIN MEMES ----------
  { id: 231, text: "\"Base is so fast my transactions arrive before my thoughts do.\"", category: "meme" },
  { id: 232, text: "\"Coinbase: 'not financial advice' — also Coinbase: builds Base.\"", category: "meme" },
  { id: 233, text: "\"Trying to find a slow Base block is like trying to find my profits.\"", category: "meme" },
  { id: 234, text: "\"Base users see $0.02 gas and think they’re royalty.\"", category: "meme" },
  { id: 235, text: "\"If Base were a person, it would say 'I told you so' every block.\"", category: "meme" },
  { id: 236, text: "\"Me bridging to Base like I’m boarding a spaceship.\"", category: "meme" },
  { id: 237, text: "\"Seeing Base pump and telling everyone 'I knew it' — I didn’t.\"", category: "meme" },
  { id: 238, text: "\"When your Base transaction fails, you instantly question reality.\"", category: "meme" },
  { id: 239, text: "\"Wen airdrop? — Base devs silently looking away.\"", category: "meme" },
  { id: 240, text: "\"I use Base not because I'm smart, but because I'm tired of gas fees.\"", category: "meme" },
  { id: 241, text: "\"Base users when gas hits $0.03: 'is everything okay??'\"", category: "meme" },
  { id: 242, text: "\"Every new Base project looks promising until I buy it.\"", category: "meme" },
  { id: 243, text: "\"Base feels like web3 but without the trauma… yet.\"", category: "meme" },
  { id: 244, text: "\"Bridge to Base? More like bridge to new mistakes.\"", category: "meme" },
  { id: 245, text: "\"My bags on Base are heavier than optimism can handle.\"", category: "meme" },
  { id: 246, text: "\"Base + memes = personality upgrade.\"", category: "meme" },
  { id: 247, text: "\"If Base had a dating app, it would match me with more gambling.\"", category: "meme" },
  { id: 248, text: "\"I trust Base more than my bank account. That’s concerning.\"", category: "meme" },
  { id: 249, text: "\"Only on Base can you lose money so cheaply.\"", category: "meme" },
  { id: 250, text: "\"Base isn’t L2 — it’s LFG2.\"", category: "meme" },

  // +10 nouvelles
  { id: 251, text: "\"I bridged to Base once. Now I bridge emotionally every day.\"", category: "meme" },
  { id: 252, text: "\"Base users be like: 'gas is too high' when it hits $0.04.\"", category: "meme" },
  { id: 253, text: "\"On Base, everything is fast — except my decision-making.\"", category: "meme" },
  { id: 254, text: "\"I saw a pump on Base and instantly blamed Coinbase.\"", category: "meme" },
  { id: 255, text: "\"Base transactions confirm faster than my excuses.\"", category: "meme" },
  { id: 256, text: "\"If Base had feelings, it would be tired of my rug pulls.\"", category: "meme" },
  { id: 257, text: "\"When the network is quiet and I think it's my fault.\"", category: "meme" },
  { id: 258, text: "\"Bridging to Base feels like entering the cheat code zone.\"", category: "meme" },
  { id: 259, text: "\"Base is blue, my bags are too.\"", category: "meme" },
  { id: 260, text: "\"If patience is a skill, waiting for the next Base pump is my training arc.\"", category: "meme" },

  // ---------- ULTRA-DEGEN ----------
  { id: 261, text: "\"I don’t invest. I degen with confidence.\"", category: "meme" },
  { id: 262, text: "\"Rugged? No problem, I'll try again tomorrow.\"", category: "meme" },
  { id: 263, text: "\"My risk management strategy is vibes.\"", category: "meme" },
  { id: 264, text: "\"Saw a coin with zero liquidity. Bought it anyway.\"", category: "meme" },
  { id: 265, text: "\"I don't chase pumps. Pumps chase my FOMO.\"", category: "meme" },
  { id: 266, text: "\"Every shitcoin is a life lesson disguised as opportunity.\"", category: "meme" },
  { id: 267, text: "\"I’ve never met a high-risk play I didn’t like.\"", category: "meme" },
  { id: 268, text: "\"Diversification? Bro, I YOLO.\"", category: "meme" },
  { id: 269, text: "\"The chart said no. My heart said yes.\"", category: "meme" },
  { id: 270, text: "\"I buy dips so deep they look like graves.\"", category: "meme" },
  { id: 271, text: "\"My investment plan is 95% praying, 5% clicking confirm.\"", category: "meme" },
  { id: 272, text: "\"Made money once. Still trying to recreate the moment.\"", category: "meme" },
  { id: 273, text: "\"If the dev is anonymous, I’m in.\"", category: "meme" },
  { id: 274, text: "\"I don’t need alpha. I need supervision.\"", category: "meme" },
  { id: 275, text: "\"In degen we trust. In charts we cry.\"", category: "meme" },
  { id: 276, text: "\"Being early is fun until you're early to a rug.\"", category: "meme" },
  { id: 277, text: "\"Zero sleep, zero plan, 100% conviction.\"", category: "meme" },
  { id: 278, text: "\"If it’s down -90%, it’s basically a bargain.\"", category: "meme" },
  { id: 279, text: "\"I don’t rug, I just relocate liquidity.\"", category: "meme" },
  { id: 280, text: "\"My wallet: chaos. My mind: also chaos.\"", category: "meme" },

  // + 10 nouvelles
  { id: 281, text: "\"I don’t invest responsibly — I invest romantically.\"", category: "meme" },
  { id: 282, text: "\"Saw a coin trending for 12 seconds, instantly bought it.\"", category: "meme" },
  { id: 283, text: "\"My TP is hope. My SL is tears.\"", category: "meme" },
  { id: 284, text: "\"If the dev is doxxed, it's too stable for me.\"", category: "meme" },
  { id: 285, text: "\"I don’t chase green candles. I sprint after them.\"", category: "meme" },
  { id: 286, text: "\"Charts go down? Perfect time to double down on denial.\"", category: "meme" },
  { id: 287, text: "\"I only hold blue chips: sadness, regret, and delusion.\"", category: "meme" },
  { id: 288, text: "\"My strategy: ignore everything and pray for a miracle.\"", category: "meme" },
  { id: 289, text: "\"I don't take profits. I take personality damage.\"", category: "meme" },
  { id: 290, text: "\"If losing money was an esport, I'd be world champion.\"", category: "meme" },

  // ---------- TRADER / NFT / AIRDROP ----------
  { id: 291, text: "\"NFT profile picture, bank account NPC.\"", category: "meme" },
  { id: 292, text: "\"Bought an NFT for the art. Stayed for the disappointment.\"", category: "meme" },
  { id: 293, text: "\"Good traders use TA. Great traders use cope.\"", category: "meme" },
  { id: 294, text: "\"The moment you sell is the moment it pumps.\"", category: "meme" },
  { id: 295, text: "\"Minted an NFT. Now I morally own a JPEG.\"", category: "meme" },
  { id: 296, text: "\"Airdrop hunters reading docs like it's literature.\"", category: "meme" },
  { id: 297, text: "\"My trading plan is: be wrong, stay wrong, hope right.\"", category: "meme" },
  { id: 298, text: "\"Checking OpenSea floor prices like it’s my blood pressure.\"", category: "meme" },
  { id: 299, text: "\"Every NFT drop: 1 winner, 10,000 bagholders.\"", category: "meme" },
  { id: 300, text: "\"I chase airdrops harder than dreams.\"", category: "meme" },
  { id: 301, text: "\"Day trading: the art of losing money slowly.\"", category: "meme" },
  { id: 302, text: "\"TA told me to sell. My ego told me to HODL.\"", category: "meme" },
  { id: 303, text: "\"Mint first, ask questions never.\"", category: "meme" },
  { id: 304, text: "\"Airdrops are like lotteries for nerds.\"", category: "meme" },
  { id: 305, text: "\"NFT community: 90% memes, 10% hopium.\"", category: "meme" },
  { id: 306, text: "\"My PnL is just a long-term practical joke.\"", category: "meme" },
  { id: 307, text: "\"The chart said down. I said 'how far?'.\"", category: "meme" },
  { id: 308, text: "\"Alpha is like sleep. Everyone wants it, nobody has it.\"", category: "meme" },
  { id: 309, text: "\"I don’t buy NFTs. I adopt them.\"", category: "meme" },
  { id: 310, text: "\"Everything I mint becomes a lesson.\"", category: "meme" },

  // +10 nouvelles
  { id: 311, text: "\"NFT community meetings are just group therapy sessions.\"", category: "meme" },
  { id: 312, text: "\"My NFTs are worth less than the gas I paid to mint them.\"", category: "meme" },
  { id: 313, text: "\"Airdrop guides look like treasure maps with sadness at the end.\"", category: "meme" },
  { id: 314, text: "\"I trade using a technique called 'emotional analysis'.\"", category: "meme" },
  { id: 315, text: "\"NFT floor down? Just means it’s on sale. Copium activated.\"", category: "meme" },
  { id: 316, text: "\"The only thing I farm is disappointment.\"", category: "meme" },
  { id: 317, text: "\"Why do I buy NFTs? I don’t know, ask my FOMO.\"", category: "meme" },
  { id: 318, text: "\"I don’t chase airdrops. I haunt them.\"", category: "meme" },
  { id: 319, text: "\"The chart goes up? Bull market confirmed. The chart goes down? Manipulation.\"", category: "meme" },
  { id: 320, text: "\"If my PnL was an NFT, it’d be a cursed legendary.\"", category: "meme" },

];
